/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_genedock_sdk_internal_compress_DSRCImpl */

#ifndef _Included_com_genedock_sdk_internal_compress_DSRCImpl
#define _Included_com_genedock_sdk_internal_compress_DSRCImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_genedock_sdk_internal_compress_DSRCImpl
 * Method:    decompress
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_genedock_sdk_internal_compress_DSRCImpl_decompress
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_genedock_sdk_internal_compress_DSRCImpl
 * Method:    compress
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_genedock_sdk_internal_compress_DSRCImpl_compress
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
